name: Daily Bible Push
on:
  schedule:
    - cron: '0 1 * * *'
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: pip install line-bot-sdk
      - name: Trigger and Push to LINE
        env:
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
        run: |
          python -c "
          import os
          from linebot import LineBotApi
          from linebot.models import TextSendMessage
          
          token = os.environ['LINE_TOKEN']
          my_user_id = 'Uf166c741223bc8ee5d82fd1fd9f4df86'
          
          line_api = LineBotApi(token)
          line_api.push_message(my_user_id, TextSendMessage(text='【自動化】系統連線驗證成功！'))
          print('發送成功！')
          "
